# By default, Spring Boot configures the application to connect to an in-memory store with the username sa and an empty password.
configuration:
  trace: true
spring:
  datasource:
    url: jdbc:h2:~/data/store;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console.settings.web-allow-others: false
  messages:
    basename: lang/messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

springdoc:
  writer-with-order-by-keys: true

logging: #This configuration is to register inside the console just Info level and DEBUG trace
  level:
    root: INFO
    com.anthony.product: DEBUG

# App Properties
app:
  jwt:
    Secret: SecretKey012345678901234567890123456789012345678901234567890123456789
    ExpirationMs: 3600000
    refreshExpirationDateInMs: 86400000