# By default, Spring Boot configures the application to connect to an in-memory store with the username sa and an empty password.

spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console.settings.web-allow-others: false