apiVersion: v1
kind: Service
metadata:
  name: product-ms-k8s-service
  namespace: springboot-product-ms
spec:
  selector:
    app: product-ms-k8s-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer