# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://github.com/marketplace/actions/jacoco-report

name: Measure coverage jacoco

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

#This is a variable of min-coverage
env:
  PERCENTAGE: 60.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        
# https://github.com/marketplace/actions/jacoco-report
# min-coreage-overall: property overrides what is declared in gradle
    - name: Add Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GH_TOKEN }}
        min-coverage-overall: ${{ env.PERCENTAGE }}
        min-coverage-changed-files: 60
        
    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
        
    - name: Fail PR if overall coverage is less than ${{ env.PERCENTAGE }}%
      if: ${{ steps.jacoco.outputs.coverage-overall < env.PERCENTAGE }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Overall coverage is less than 80%!')
  
